---
- name: Create default VPC
  hosts: localhost
  connection: local
  gather_facts: false

  module_defaults:
    group/aws:
      region: us-east-2

  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: vpc-demo
        cidr_block: 172.31.0.0/16
      register: _vpc

    - name: Create subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ _vpc.vpc.id }}"
        az: us-east-2a
        cidr: 172.31.0.0/20
      register: _subnet

    - name: Create internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ _vpc.vpc.id }}"
      register: _igw

    - name: Create route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ _vpc.vpc.id }}"
        subnets: "{{ _subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ _igw.gateway_id }}"
          # - dest: 172.31.0.0/16
          #   gateway_id: local

    - name: Create security group
      amazon.aws.ec2_group:
        name: security-demo
        description: allow ssh, http, https
        vpc_id: "{{ _vpc.vpc.id }}"
        rules:
          - proto: tcp
            ports: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports: 443
            cidr_ip: 0.0.0.0/0

    - name: Create EC2 key
      amazon.aws.ec2_key:
        name: ansible
      register: _key

    - name: Display key info
      ansible.builtin.debug:
        var: _key.key

    - name: Save key file
      ansible.builtin.copy:
        content: "{{ _key.key.private_key }}"
        dest: "{{ playbook_dir }}/ansible.pem"
        mode: '400'
      when: _key.key.private_key is defined
